name: Release

on:
  push:
    tags:
      - "release/*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: flrapp/.github/.github//workflows/docker-build-push.yml@main
    with:
      image-name: ghcr.io/flrapp/flare-ui
      dockerfile-path: .
    secrets: inherit
